const planetData = [
  {
    name: 'Mercury',
    slug: 'mercury',
    type: 'Terrestrial',
    diameter_km: 4879,
    mass_kg: 3.3011e23,
    gravity: 3.7,
    orbital_speed: 47.87,
    orbital_period_days: 88,
    distance_from_sun_km: 57900000,
    hasMoon: false,
    moons: 0,
    atmosphere: ['Oxygen', 'Sodium', 'Hydrogen'],
    discovered: 'Known since ancient times',
    distance: 5,
    size: 0.4,
    speed: 0.6,
    color: '#aaa',
    texture: '/planets/mercury.png'
  },
  {
    name: 'Venus',
    slug: 'venus',
    type: 'Terrestrial',
    diameter_km: 12104,
    mass_kg: 4.8675e24,
    gravity: 8.87,
    orbital_speed: 35.02,
    orbital_period_days: 225,
    distance_from_sun_km: 108200000,
    hasMoon: false,
    moons: 0,
    atmosphere: ['Carbon Dioxide', 'Nitrogen'],
    discovered: 'Known since ancient times',
    distance: 7,
    size: 0.8,
    speed: 0.3,
    color: '#f5deb3',
    texture: '/planets/venus.png'
  },
  {
    name: 'Earth',
    slug: 'earth',
    type: 'Terrestrial',
    diameter_km: 12742,
    mass_kg: 5.972e24,
    gravity: 9.807,
    orbital_speed: 29.78,
    orbital_period_days: 365.25,
    distance_from_sun_km: 149600000,
    hasMoon: true,
    moons: 1,
    atmosphere: ['Nitrogen', 'Oxygen', 'Argon', 'CO2'],
    discovered: 'Known since ancient times',
    distance: 10,
    size: 1,
    speed: 0.2,
    color: '#1e90ff',
    texture: '/planets/earth.png'
  },
  {
    name: 'Mars',
    slug: 'mars',
    type: 'Terrestrial',
    diameter_km: 6779,
    mass_kg: 6.4171e23,
    gravity: 3.71,
    orbital_speed: 24.07,
    orbital_period_days: 687,
    distance_from_sun_km: 227900000,
    hasMoon: true,
    moons: 2,
    atmosphere: ['Carbon Dioxide', 'Argon', 'Nitrogen'],
    discovered: 'Known since ancient times',
    distance: 13,
    size: 0.6,
    speed: 0.1,
    color: '#b22222',
    texture: '/planets/mars.png'
  },
  {
    name: 'Jupiter',
    slug: 'jupiter',
    type: 'Gas Giant',
    diameter_km: 139820,
    mass_kg: 1.898e27,
    gravity: 24.79,
    orbital_speed: 13.07,
    orbital_period_days: 4331,
    distance_from_sun_km: 778500000,
    hasMoon: true,
    moons: 95,
    atmosphere: ['Hydrogen', 'Helium'],
    discovered: 'Known since ancient times',
    distance: 17,
    size: 1.8,
    speed: 0.08,
    color: '#d2b48c',
    texture: '/planets/jupiter.png'
  },
  {
    name: 'Saturn',
    slug: 'saturn',
    type: 'Gas Giant',
    diameter_km: 116460,
    mass_kg: 5.683e26,
    gravity: 10.44,
    orbital_speed: 9.69,
    orbital_period_days: 10747,
    distance_from_sun_km: 1434000000,
    hasMoon: true,
    moons: 146,
    atmosphere: ['Hydrogen', 'Helium'],
    discovered: 'Known since ancient times',
    distance: 21,
    size: 1.5,
    speed: 0.05,
    color: '#daa520',
    hasRing: true,
    texture: '/planets/saturn.png',
    ringTexture: '/planets/saturn_ring.png'
  },
  {
    name: 'Uranus',
    slug: 'uranus',
    type: 'Ice Giant',
    diameter_km: 50724,
    mass_kg: 8.681e25,
    gravity: 8.69,
    orbital_speed: 6.81,
    orbital_period_days: 30589,
    distance_from_sun_km: 2871000000,
    hasMoon: true,
    moons: 28,
    atmosphere: ['Hydrogen', 'Helium', 'Methane'],
    discovered: '1781 by William Herschel',
    distance: 25,
    size: 1.2,
    speed: 0.03,
    color: '#00ffff',
    texture: '/planets/uranus.png'
  },
  {
    name: 'Neptune',
    slug: 'neptune',
    type: 'Ice Giant',
    diameter_km: 49244,
    mass_kg: 1.024e26,
    gravity: 11.15,
    orbital_speed: 5.43,
    orbital_period_days: 59800,
    distance_from_sun_km: 4495000000,
    hasMoon: true,
    moons: 16,
    atmosphere: ['Hydrogen', 'Helium', 'Methane'],
    discovered: '1846 by Johann Galle',
    distance: 29,
    size: 1.1,
    speed: 0.02,
    color: '#4169e1',
    texture: '/planets/neptune.png'
  }
]

export default planetData
